services:
  db:
    container_name: db
    image: mysql:8.0.29
    ports:
      - '13306:3306'
    volumes:
      - ticket_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ticket-concurrency
      MYSQL_ROOT_PASSWORD: root
      DEFAULT_CHARACTER_SET: utf8mb4
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_general_ci
      TZ: Asia/Seoul

volumes:
  ticket_db: